name: "Trigger site publish"

on:
  push:
    branches: [main]
  workflow_dispatch:
  
concurrency:
  group: github-pages
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger creator-assertions.github.io publish
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PUBLISH_TOKEN }}
        script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'creator-assertions',
              repo: 'creator-assertions.github.io',
              workflow_id: 'publish.yml',
              ref: 'main'
            })
